#!/bin/bash

rsyn=../../rsyn

# Check if we are in the right working directory.
# TODO: Find a way to detect the correct relative directory where /rsyn is.
if [ ! -d "../../x" ]; then
	echo "Please, go to /x/script to run this script."
	exit	
fi

if [ -d "$rsyn/.git" ]; then
    # /rsyn is already a git repository
    cd $rsyn
    git pull
else
	# /rsyn is not a git repository
	tmp=$(mktemp -d)
	if [ -d "$rsyn" ]; then
		echo "Moving old rsyn folder to $tmp."	
		mv $rsyn $tmp
	fi
	echo "Cloning rsyn..."
	git clone https://github.com/rsyn/rsyn $rsyn

fi
